WITH CHILD_COUNT AS (
  SELECT PARENT_ID AS ID,
         COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
   WHERE PARENT_ID IS NOT NULL
   GROUP BY PARENT_ID
)
SELECT ED.ID,
       IFNULL(CC.CHILD_COUNT, 0) AS CHILD_COUNT
  FROM ECOLI_DATA ED
  LEFT
  JOIN CHILD_COUNT CC
    ON ED.ID = CC.ID
 ORDER BY 1;