SELECT FP.PRODUCT_ID,
       FP.PRODUCT_NAME,
       SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
  FROM FOOD_PRODUCT FP
  JOIN (SELECT PRODUCT_ID, AMOUNT
          FROM FOOD_ORDER
         WHERE YEAR(PRODUCE_DATE) = 2022
           AND MONTH(PRODUCE_DATE) = 5) FO
    ON FP.PRODUCT_ID = FO.PRODUCT_ID
 GROUP BY FP.PRODUCT_ID
 ORDER BY 3 DESC, 1;