WITH CATEGORY_MAX_PRICE AS (
  SELECT CATEGORY,
         MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
   WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
   GROUP BY CATEGORY
)
SELECT FP.CATEGORY,
       CMP.MAX_PRICE,
       FP.PRODUCT_NAME
  FROM FOOD_PRODUCT FP
  JOIN CATEGORY_MAX_PRICE CMP
    ON FP.PRICE = CMP.MAX_PRICE
   AND FP.CATEGORY = CMP.CATEGORY
 ORDER BY 2 DESC;